language: php

matrix:
  fast_finish: true
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7
    - php: hhvm
  allow_failures:
    - php: hhvm

install:
  - travis_retry composer install --no-interaction
  - composer info -i

script:
  - ./vendor/bin/phpunit