<?php $title = 'Admini';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><?php echo "Sunteti autentificat ca: <b>".$username."</b>";?></p>
<table class="table">
    <tr>
        <th>Username</th>
        <th>Nume</th>
        <th>Prenume</th>
        <th>Varsta</th>
        <th>Email</th>
        <th>Telefon</th>
        <th>Activ</th>
    </tr>
<?php foreach($admini as $admin) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($admin->username);?></td>
        <td><?php echo $this->escapeHtml($admin->nume);?></td>
        <td><?php echo $this->escapeHtml($admin->prenume);?></td>
        <td><?php echo $this->escapeHtml($admin->varsta);?></td>
        <td><?php echo $this->escapeHtml($admin->email);?></td>
        <td><?php echo $this->escapeHtml($admin->telefon);?></td>
        <td><?php echo $this->escapeHtml($admin->activ);?></td>
    </tr>
<?php endforeach; ?>
</table>