<?php
$title = 'Edit';
$this->headTitle($title);
$form = $this->form;
 $form->setAttribute('action', $this->url(
     'admin',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
   ));
?>

 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->prepare();

 echo $this->form()->openTag($form)."</br>";
 echo $this->formRow($form->get('username'))."</br>";
 echo $this->formRow($form->get('nume'))."</br>";
 echo $this->formRow($form->get('prenume'))."</br>";
 echo $this->formRow($form->get('email'))."</br>";
 echo $this->formRow($form->get('telefon'))."</br>";
 echo $this->formRow($form->get('varsta'))."</br>";
 echo $this->formSubmit($form->get('submit'))."</br>";
 echo $this->form()->closeTag();
 