<?php
$title = 'Register';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->prepare();

 echo $this->form()->openTag($form)."</br>";
 echo $this->formRow($form->get('username'))."</br>";
 echo $this->formRow($form->get('nume'))."</br>";
 echo $this->formRow($form->get('prenume'))."</br>";
 echo $this->formRow($form->get('email'))."</br>";
 echo $this->formRow($form->get('telefon'))."</br>";
 echo $this->formRow($form->get('varsta'))."</br>";
 echo $this->formRow($form->get('parola'))."</br>";
 echo $this->formRow($form->get('confirmaparola'))."</br>";
 echo $this->formSubmit($form->get('submit'))."</br>";
 echo $this->form()->closeTag();
 