<?php $title = 'Categorii';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
if(isset($form)){   
    
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('categorii'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 
} else
{
   $produsform->prepare();
    echo $this->form()->openTag($produsform);
     echo $this->formRow($produsform->get('denumire'));
     echo $this->formRow($produsform->get('brand'));
    echo $this->formRow($produsform->get('descriere'));
    foreach($numefield as $nume):
        echo $this->formRow($produsform->get($nume));
    endforeach;
    echo $this->formSubmit($produsform->get('submit'));
    echo $this->form()->closeTag();
}


