<?php $title = 'Categorii';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('categorii'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 
 if(isset($atribute)){
foreach($atribute as $atribut) :
     echo $this->escapeHtml($atribut->atribut->nume)."</br>";
endforeach; 
 }
 

